### register user
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "fullName": "newuser",
  "email": "newuser7@example.com",
  "password": "securepassword"
}

### login user
POST http://localhost:5000/api/user/login  
Content-Type: application/json

{
  "email": "newuser7@example.com",
  "password": "securepassword"
}

### register doctor
POST http://localhost:5000/api/doctor/register
Content-Type: application/json

{
  "fullName": "Dr. John Doe",
  "email": "memonyasin2007@gmail.com",
  "phone": "+1234567890",
  "password": "securepassword", 
  "specialty": "Cardiology",
  "experience": 10,
  "qualifications": ["MD"],
  "registration_number": "REG123456",
  "hospital_name": "HealthCare Hospital",
  "city": "Health City",
  "consulation_type": "Online",
  "consulation_fee": 150,
  "available_days": ["Monday", "Wednesday", "Friday"],
  "time_slots": ["10:00-12:00", "14:00-16:00"],
  "conclusion_duration": 30,
  "medical_license": "MEDLIC123456",
  "goverment_id": "GOV123456"
}

### login doctor
POST http://localhost:5000/api/doctor/login
Content-Type: application/json

{
  "email": "memonyasin2007@gmail.com",
  "password": "securepassword"
}

POST http://localhost:5000/api/doctor/logout
Content-Type: application/json

{
  "token": "<doctor_jwt_token>"
} 

### delete and create admin
GET http://localhost:5000/api/admin/create

### admin login
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
  "username" : "doctor",
  "password" : "password"
}