### register user
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "fullName": "newuser",
  "email": "newuser7@example.com",
  "password": "securepassword"
}

### login user
POST http://localhost:5000/api/user/login  
Content-Type: application/json

{
  "email": "newuser7@example.com",
  "password": "securepassword"
}

### register doctor
POST http://localhost:5000/api/doctor/register
Content-Type: application/json

{
  "fullName": "Dr. John Doe",
  "email": "memonyasin2007@gmail.com",
  "phone": "+1234567890",
  "password": "securepassword", 
  "specialty": "Cardiology",
  "licenseNumber": "LIC123456",
  "yearsOfExperience": 10,
  "clinicAddress": "123 Medical St, Health City",
  "contactNumber": "+1234567890",
  "goverment_id": "GOV123456"

}